const initialDetails = [
  {
    id: 1,
    imgPath: "../../img/blockuser1.png",
    icon: "../../img/flet-icon1.png",
    name: "Jane Doe",
    prof: "Community Tutor",
    language: "English",
    price: "IDR - 85,730.10",
    from: "IDR - 485,730.10",
  },
  {
    id: 2,
    imgPath: "../../img/blockuser2.png",
    icon: "../../img/flet-icon2.png",
    name: "Mary Rosamund",
    prof: "Community Tutor",
    language: "Spanish",
    price: "IDR - 85,730.10",
    from: "IDR - 485,730.10",
  },
  {
    id: 3,
    imgPath: "../../img/blockuser3.png",
    icon: "../../img/flet-icon3.png",
    name: "Sherlock Watson",
    prof: "Community Tutor",
    language: "English",
    price: "IDR - 85,730.10",
    from: "IDR - 485,730.10",
  },
  {
    id: 4,
    imgPath: "../../img/blockuser4.png",
    icon: "../../img/flet-icon4.png",
    name: "John Holmes",
    prof: "Community Tutor",
    language: "Spanish",
    price: "IDR - 85,730.10",
    from: "IDR - 485,730.10",
  },
  {
    id: 5,
    imgPath: "../../img/blockuser4.png",
    icon: "../../img/flet-icon5.png",
    name: "Mycroft Lestrade",
    prof: "Community Tutor",
    language: "English",
    price: "IDR - 85,730.10",
    from: "IDR - 485,730.10",
  },
];

export default initialDetails;
