const initialDetails = [
  {
    id: 1,
    stars: 4.9,
    speaks: "native",
    imgPath: "../../img/blockuser1.png",
    icon: "../../img/flet-icon1.png",
    name: "Jane Doe",
    prof: "Community Tutor",
    language: "English",
    price: "IDR - 85,730.10",
    from: "IDR - 485,730.10",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Feugiat aliquam integer sit mauris sit. Pellentesque urna, adipiscing at aliquam tempor non. Lectus bibendum sollicitudin aliquet id...",
    workingHours: "8:00-15:00",
    holiday: "Monday",
    holidayNacional: "Sunday",
  },
  {
    id: 2,
    stars: 4.5,
    speaks: "-",
    imgPath: "../../img/blockuser2.png",
    icon: "../../img/flet-icon2.png",
    name: "Mary Rosamund",
    prof: "Community Tutor",
    language: "Spanish",
    price: "IDR - 85,730.10",
    from: "IDR - 485,730.10",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Feugiat aliquam integer sit mauris sit. Pellentesque urna, adipiscing at aliquam tempor non. Lectus bibendum sollicitudin aliquet id...",
    workingHours: "8:00-14:00",
    holiday: "Sunday",
    holidayNacional: "Sunday",
  },
  {
    id: 3,
    stars: 5,
    speaks: "native",
    imgPath: "../../img/blockuser3.png",
    icon: "../../img/flet-icon3.png",
    name: "Sherlock Watson",
    prof: "Community Tutor",
    language: "English",
    price: "IDR - 85,730.10",
    from: "IDR - 485,730.10",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Feugiat aliquam integer sit mauris sit. Pellentesque urna, adipiscing at aliquam tempor non. Lectus bibendum sollicitudin aliquet id...",
    workingHours: "8:00-18:00",
    holiday: "Monday",
  },
  {
    id: 4,
    stars: 4,
    speaks: "native",
    imgPath: "../../img/blockuser4.png",
    icon: "../../img/flet-icon4.png",
    name: "John Holmes",
    prof: "Community Tutor",
    language: "Spanish",
    price: "IDR - 85,730.10",
    from: "IDR - 485,730.10",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Feugiat aliquam integer sit mauris sit. Pellentesque urna, adipiscing at aliquam tempor non. Lectus bibendum sollicitudin aliquet id...",
    workingHours: "8:00-15:00",
    holiday: "Sunday",
    holidayNacional: "Sunday",
  },
  {
    id: 5,
    stars: 4.1,
    speaks: "-",
    imgPath: "../../img/blockuser4.png",
    icon: "../../img/flet-icon5.png",
    name: "Mycroft Lestrade",
    prof: "Community Tutor",
    language: "English",
    price: "IDR - 85,730.10",
    from: "IDR - 485,730.10",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Feugiat aliquam integer sit mauris sit. Pellentesque urna, adipiscing at aliquam tempor non. Lectus bibendum sollicitudin aliquet id...",
    workingHours: "12:00-15:00",
    holiday: "Sunday",
    holidayNacional: "Sunday",
  },
];

export default initialDetails;
